# Generated by Django 3.2 on 2021-05-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0002_alter_website_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_block',
            name='align',
            field=models.CharField(choices=[('center', 'center'), ('left', 'left'), ('right', 'right')], default='center', max_length=10),
        ),
    ]
