# Generated by Django 3.2 on 2021-05-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0004_alter_text_block_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_block',
            name='text',
            field=models.CharField(blank=True, default='j', max_length=10000),
        ),
    ]
