# Generated by Django 3.2 on 2021-05-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0008_text_block_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med', models.URLField(max_length=1000, null=True)),
                ('webp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcore.webpage')),
            ],
        ),
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('text2', models.CharField(max_length=100, null=True)),
                ('align', models.CharField(max_length=50, null=True)),
                ('dc', models.CharField(max_length=20, null=True)),
                ('pag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcore.webpage')),
            ],
        ),
    ]
