# Generated by Django 3.2 on 2021-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0009_contents_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='resourcetype',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
