# Generated by Django 3.2 on 2021-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0010_media_resourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='align',
            field=models.CharField(default='left', max_length=50, null=True),
        ),
    ]
