# Generated by Django 3.2 on 2021-06-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0012_testtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtext',
            name='title',
            field=models.CharField(default='untitled', max_length=1000),
        ),
    ]
