# Generated by Django 3.2 on 2021-06-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0013_testtext_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtext',
            name='site',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='webcore.website'),
        ),
    ]
