# Generated by Django 3.2 on 2021-06-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0016_testtext_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtext',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
    ]
