# Generated by Django 3.2 on 2021-07-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0017_testtext_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=254)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcore.testtext')),
            ],
        ),
    ]
